In [1]:
import pandas as pd
import numpy as np

Load Dataset

In [2]:
df = pd.read_csv("../data/uber_trips_dataset_50k.csv")

df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000

Check structure

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   trip_id         50000 non-null  int64
 1   driver_id       50000 non-null  int64
 2   rider_id        50000 non-null  int64
 3   city            50000 non-null  object
 4   pickup_lat      50000 non-null  float64
 5   pickup_lng      50000 non-null  float64
 6   drop_lat        50000 non-null  float64
 7   drop_lng        50000 non-null  float64
 8   distance_km     50000 non-null  float64
 9   fare_amount     50000 non-null  float64
 10  status          50000 non-null  object
 11  payment_method  50000 non-null  object
 12  pickup_time     50000 non-null  object
 13  drop_time       50000 non-null  object
dtypes: float64(6), int64(3), object(5)
memory usage: 5.3+ MB

In [4]:
df.shape

(50000, 14)

Data Cleaning---Missing values remove

In [5]:
df.isnull().sum()

trip_id           0
driver_id         0
rider_id          0
city              0
pickup_lat        0
pickup_lng        0
drop_lat          0
drop_lng          0
distance_km       0
fare_amount       0
status            0
payment_method    0
pickup_time       0
drop_time         0
dtype: int64

Remove missing values

In [6]:
df = df.dropna()

Remove duplicates

In [7]:
df = df.drop_duplicates()

Convert Date Column

In [8]:
df["pickup_time"] = pd.to_datetime(df["pickup_time"])

Time Features create karo

In [9]:
df["Hour"] = df["pickup_time"].dt.hour
df["Day"] = df["pickup_time"].dt.day
df["Month"] = df["pickup_time"].dt.month

In [10]:
df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,Hour,Day,Month
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000,0,1,1
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000,0,1,1
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000,0,1,1
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000,0,1,1
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000,0,1,1

Daily Ride Distribution

In [11]:
daily_rides = df.groupby("Day").size()

print(daily_rides)

Day
1     2880
2     2880
3     2880
4     2480
5     1440
6     1440
7     1440
8     1440
9     1440
10    1440
11    1440
12    1440
13    1440
14    1440
15    1440
16    1440
17    1440
18    1440
19    1440
20    1440
21    1440
22    1440
23    1440
24    1440
25    1440
26    1440
27    1440
28    1440
29    1440
30    1440
31    1440
dtype: int64

Monthly Ride Distribution

In [12]:
daily_rides = df.groupby(["Month","Day"]).size()

print(daily_rides)

Month  Day
1      1      1440
       2      1440
       3      1440
       4      1440
       5      1440
       6      1440
       7      1440
       8      1440
       9      1440
       10     1440
       11     1440
       12     1440
       13     1440
       14     1440
       15     1440
       16     1440
       17     1440
       18     1440
       19     1440
       20     1440
       21     1440
       22     1440
       23     1440
       24     1440
       25     1440
       26     1440
       27     1440
       28     1440
       29     1440
       30     1440
       31     1440
2      1      1440
       2      1440
       3      1440
       4      1040
dtype: int64

In [13]:
monthly_rides = df.groupby("Month").size()

print(monthly_rides)

Month
1    44640
2     5360
dtype: int64

Peak Hours Analysis

In [14]:
peak_hours = df.groupby("Hour").size()

print(peak_hours)

Hour
0     2100
1     2100
2     2100
3     2100
4     2100
5     2100
6     2100
7     2100
8     2100
9     2100
10    2100
11    2100
12    2100
13    2100
14    2100
15    2100
16    2100
17    2060
18    2040
19    2040
20    2040
21    2040
22    2040
23    2040
dtype: int64

In [15]:
peak_hours.idxmax()

np.int32(0)

In [16]:
peak_hours.max()

2100

Busiest City / Zone

In [17]:
df["city"].value_counts()

city
Boston           8454
San Francisco    8401
Chicago          8345
Los Angeles      8315
New York         8247
Seattle          8238
Name: count, dtype: int64

In [18]:
df["city"].value_counts().idxmax()

'Boston'

Average Fare Analysis

In [19]:
df["fare_amount"].mean()

np.float64(15.9762054)

Revenue Calculation

In [20]:
df["Revenue"] = df["fare_amount"]

In [21]:
df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,Hour,Day,Month,Revenue
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000,0,1,1,10.71
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000,0,1,1,22.41
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000,0,1,1,12.91
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000,0,1,1,15.70
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000,0,1,1,19.15

Revenue per City

In [22]:
df.groupby("city")["Revenue"].sum()

city
Boston           135704.41
Chicago          132693.51
Los Angeles      131156.08
New York         132351.73
San Francisco    134611.24
Seattle          132293.30
Name: Revenue, dtype: float64

In [23]:
df.groupby("city")["Revenue"].sum().idxmax()

'Boston'

Outliers Check (NumPy)

In [24]:
np.mean(df["fare_amount"])

np.float64(15.9762054)

In [25]:
np.std(df["fare_amount"])

6.274343318866979

In [26]:
np.max(df["fare_amount"])

50.67

Clean dataset save

In [27]:
df.to_csv("../outputs/cleaned_uber_data.csv", index=False)